### ISSUE TITLE
Missing dependency `tiny-json-http`

### ISSUE THREAD

**Issue by macdonst** [ryanbethel/arc-plugin-oauth#1]
I've added `arc-plugin-oauth` to my project `app.arc` file:

```
@app
arc-fnh

@http
get /

@plugins
arc-plugin-oauth

@oauth
use-mock true
```

But when I try to run the sandbox I get the following error.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tiny-json-http' imported from $PROJECT_NAME/node_modules/arc-plugin-oauth/src/src/http/get-auth/oauth.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I think you'll need to make it a dependency or a peerDependency in order for it to work in sandbox.

**Comment by ryanbethel** [comment]
Thanks! Fixed in v0.0.9.
