### ISSUE TITLE
/login route can't find index.js imported from line 2 when deployed to AWS

### ISSUE THREAD

**Issue by macdonst** [ryanbethel/arc-plugin-oauth#2]
When the plugin is deployed to AWS the line:

```javascript
import arcOauth from '../../../index.js'
```

Which kinda makes sense as if you go 3 folders back from the lambda you are no longer in the lambda.

The stack trace is:

```
2022-03-22T03:31:09.885Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '/index.js' imported from /var/task/index.mjs",
    "code": "ERR_MODULE_NOT_FOUND",
    "stack": [
        "Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/index.js' imported from /var/task/index.mjs",
        "    at new NodeError (internal/errors.js:322:7)",
        "    at finalizeResolution (internal/modules/esm/resolve.js:308:11)",
        "    at moduleResolve (internal/modules/esm/resolve.js:731:10)",
        "    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)",
        "    at Loader.resolve (internal/modules/esm/loader.js:89:40)",
        "    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)",
        "    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)",
        "    at link (internal/modules/esm/module_job.js:75:36)",
        "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)",
        "    at /var/runtime/deasync.js:23:15"
    ]
}
```

**Comment by ryanbethel** [comment]
Thanks! Fixed in v0.0.9.

**Comment by snelgrove** [comment]
Just trying this plugin for the first time. Did this issue get reintroduced [recently](https://github.com/ryanbethel/arc-plugin-oauth/commit/836abed2e88f637a3d12bb5dafd0168cd8c47d37)? In staging, my `...GetLoginHTTPLambda...` lambda has no such relative path.

**Comment by ryanbethel** [comment]
@snelgrove It may have. Thanks for reporting it. I will look into it.
